baseURL: https://selmankon.com
languageCode: en-us
defaultContentLanguage: en
title: selman konakçı
theme: cupper-hugo-theme
# googleAnalytics: UA-123456789-1
# disqusShortname: selmankon
enableGitInfo: true

# taxonomies:
  # tag: tags

permalinks:
  post: /:filename/

imaging:
  quality: 99

params:
  description: \%60water\%40unsatisfied💯
  homeMetaContent: selmankon.com
  # footer: Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme).  
  # For more date formats see https://gohugo.io/functions/format/
  dateFormat: January 2006
  # codePenUser: someUser
  katex: false
  hideHeaderLinks: false
  search: false
  showThemeSwitcher: false
  defaultDarkTheme: false
  moveFooterToHeader: false
  # navTitleText: Cupper Theme
  logoAlt: kenpū denki berserk
  customCss:
    #- css/custom_01.css
  customJs:
    #- js/custom_01.js

menu:
  nav:
    - name: home
      url: /
      weight: 1
    - name: about-me
      url: /about-me/
      weight: 2
    - name: blog
      url: https://blog.selmankon.com
      weight: 3
    - name: projects
      url: /projects/
      weight: 4
    - name: contact-me
      url: /contact-me/
      weight: 5

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
